name: Elm CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - name: Compile Elm
        run: elm make src/*.elm