name: Elm CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.NVMRC }}
      - run: npm ci
      - name: Generate elm-land stuff
        run: elm-land generate
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - name: Compile Elm
        run: elm make src/*.elm